name: Deploy to Firebase

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
          
      - name: Run tests
        run: |
          # Add test command here when you have tests
          echo "Tests would run here"
          
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
          
      - name: Authorize Docker push
        run: gcloud auth configure-docker
        
      - name: Build and push Docker image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/monte-carlo-simulator:${{ github.sha }} .
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/monte-carlo-simulator:${{ github.sha }}
          
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy monte-carlo-simulator \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/monte-carlo-simulator:${{ github.sha }} \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated
            
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          channelId: live
          projectId: ${{ secrets.FIREBASE_PROJECT_ID }}
